name: Cypress Tests

on: 
  schedule:
    - cron: "0 14 * * 1-5"
 
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run run:record
