name: Cypress Tests

on: push
 
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx cypress run

      - name: Extract test results
        run: |
          suites=$(jq -r '.totals.suites' cypress/results.json)
          tests=$(jq -r '.totals.tests' cypress/results.json)
          passed=$(jq -r '.totals.passed' cypress/results.json)
          failed=$(jq -r '.totals.failed' cypress/results.json)

      - name: Send Slack Notification on Failure
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_CHANNEL: cypresstest
          SLACK_COLOR: "#9e2a2b"
          #SLACK_ICON: https://someurl.com/logo.png
          SLACK_MESSAGE: "Failed execution on production build"
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
