name: Cypress Test 
on: 
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress open
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Pruebas ${GITHUB_REPOSITORY}
          body: El resultado de las pruebas fue ${{ job.status }}
          to: jairob92@gmail.com

