name: Cypress Tests

on: push
 
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run cypress:run-json

      - name: Print test results
        if: ${{ always() }}
        run: echo 'Imprimiendo resultados de prueba' && cat cypress/results.json

      - name: Extract test results
        if: ${{ always() }}
        run: |
          suites=$(jq -r '.totals.suites' cypress/results.json)
          tests=$(jq -r '.totals.tests' cypress/results.json)
          passed=$(jq -r '.totals.passed' cypress/results.json)
          failed=$(jq -r '.totals.failed' cypress/results.json)
         
      - name: Send Slack notification
        if: ${{ always() }}
        env:
          SLACK_MESSAGE: "Se ejecutaron $tests tests, $passed pasaron y $failed fallaron"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_CHANNEL: cypresstest
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "'"${SLACK_MESSAGE}"'"}' $SLACK_WEBHOOK

          
