name: Cypress Test 
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress run
      - name: Notify results by email
        uses: dawidd6/action-send-mail@v3
        with:
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 465
          SMTP_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          MAIL_FROM: jairob92@gmail.com
          MAIL_TO: jairo.bermudez@afex.cl
          MAIL_SUBJECT: Cypress test results
          MAIL_BODY: |
            The Cypress tests have finished. Here are the results:

            ${{ steps.test.outputs.cypressResults }}

        env:
          TZ: America/Los_Angeles
