name: Cypress Test 
on: 
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress open
      - name: Send email with results
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: 'Resultados de las pruebas de Cypress'
          body: 'Los resultados de las pruebas de Cypress'
          to: jairob92@gmail.com
          from: jairo.bermudez@afex.cl
