name: Cypress Test 
on: 
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress open
      - name: Send email
      - uses: cinotify/github-action@main
        with:
          to: 'jairob92@gmail.com'
          subject: 'building main'
          body: 'This is a notification from GitHub actions.'

