name: Cypress Test 
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress open
      - name: Send Slack Notification on Failure
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cypresstest
          SLACK_COLOR: "#9e2a2b"
          #SLACK_ICON: https://someurl.com/logo.png
          SLACK_MESSAGE: "Failed execution on production build"
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
      - name: Run Cypress tests
        run: |
          export SLACK_WEBHOOK=$SLACK_WEBHOOK
           npx cypress run --headless --browser chrome
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          CYPRESS_CACHE_FOLDER: ${{ runner.temp }}/.cache/Cypress
          CYPRESS_VIDEO: false
          SLACK_CHANNEL: cypresstest
