name: Cypress Test 
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress open
      - name: Send Slack Notification on Failure
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cypresstest
          SLACK_COLOR: "#9e2a2b"
          #SLACK_ICON: https://someurl.com/logo.png
          SLACK_MESSAGE: "Failed execution on production build"
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
      - name: Send Slack notification
        if: always()
        uses: slack/webhook@v1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: cypresstest
          SLACK_TITLE: ${{ job.status }}
        with:
          payload: '{"text": "Cypress tests result:\n\nTotal tests: ${{ env.CYPRESS_TOTAL_TESTS }}\nSuccessful tests: ${{ env.CYPRESS_PASSED_TESTS }}\nFailed tests: ${{ env.CYPRESS_FAILED_TESTS }}"}'
