name: Cypress Tests

on: push
 
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run cypress:run-json

      - name: Extract test results
        run: |
          suites=$(cat cypress/results.json | jq '.totalSuites')
          tests=$(cat cypress/results.json | jq '.totalTests')
          passes=$(cat cypress/results.json | jq '.totalPassed')
          failures=$(cat cypress/results.json | jq '.totalFailed')
          echo "Cypress results:"
          echo "Suites: $suites"
          echo "Tests: $tests"
          echo "Passed: $passes"
          echo "Failed: $failures"

      - name: Send Slack Notification on Failure
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_CHANNEL: cypresstest
          SLACK_COLOR: "#9e2a2b"
          #SLACK_ICON: https://someurl.com/logo.png
          SLACK_MESSAGE: "Failed execution on production build"
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
