name: Cypress Tests

on: push
 
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run cypress:run-json

      - name: Print test results
        if: ${{ always() }}
        run: echo 'Imprimiendo resultados de prueba' && cat cypress/results.json

      - name: Extract test results
        if: ${{ always() }}
        run: |
         node -e '
         const fs = require("fs");

         const data = JSON.parse(fs.readFileSync("cypress/results.json"));

         const suites = totals.suites;
         const tests =  totals.tests;
         const passed = totals.passed;
         const failed = totals.failed;
         ' 
      - name: Print test results
        if: ${{ always() }}
        run: |
          echo "Suites: $suites"
          echo "Tests: $tests"
          echo "Passed: $passed"
          echo "Failed: $failed"
          
      - name: Send Slack notification
        if: ${{ always() }}
        env:
          SLACK_MESSAGE: "Se ejecutaron ${tests} tests, ${passed} pasaron y ${failed} fallaron"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_CHANNEL: cypresstest
          SLACK_EMOJI: ":robot_face:"
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "'"${SLACK_MESSAGE}"'"}' $SLACK_WEBHOOK

          
