name: Cypress Test 
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress open
      - name: Send Slack Notification on Failure
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cypresstest
          SLACK_COLOR: ${{ steps.cypress.outputs.passed == 'true' && '#36a64f' || '#9e2a2b' }}
          SLACK_TITLE: ${{ steps.cypress.outputs.passed == 'true' && 'Cypress Tests Passed' || 'Cypress Tests Failed' }}
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_MESSAGE: |
            Total Tests: `${{ steps.cypress.outputs.totalTests }}`
            Passed: `${{ steps.cypress.outputs.passes }}`
            Failed: `${{ steps.cypress.outputs.failures }}`

