name: Cypress Test 
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress open
      - name: Send Slack Notification on Failure
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cypresstest
          SLACK_COLOR: "#9e2a2b"
          #SLACK_ICON: https://someurl.com/logo.png
          SLACK_MESSAGE: "Failed execution on production build"
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Run Cypress tests
        run: |
          npx cypress run --headless --browser chrome
        env:
          CYPRESS_CACHE_FOLDER: ${{ runner.temp }}/.cache/Cypress
          CYPRESS_VIDEO: false
          id: cypress
          
      - name: Send Slack notification
        env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          total=$(grep -oP '(\d+) total' ${{ steps.cypress.outputs.runLogs }} | cut -d' ' -f1)
          passed=$(grep -oP '(\d+) passing' ${{ steps.cypress.outputs.runLogs }} | cut -d' ' -f1)
          failed=$(grep -oP '(\d+) failing' ${{ steps.cypress.outputs.runLogs }} | cut -d' ' -f1)
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Cypress tests summary:\n- Total tests: '$total'\n- Passed tests: '$passed'\n- Failed tests: '$failed'"}' $SLACK_WEBHOOK_URL

