name: Cypress Test 
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress.io
        uses: cypress-io/github-action@37c511bc322f112c2dd629d3610f4f096bc80096
        with: 
          start: npx cypress open
      - name: Send Slack Notification on Failure
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cypresstest
          SLACK_COLOR: "#9e2a2b"
          #SLACK_ICON: https://someurl.com/logo.png
          SLACK_MESSAGE: "Failed execution on production build"
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
      - name: Send Slack message
        if: ${{ always() }}
        run: |
          failed=$(jq '.runs[].totals.failed' cypress/results.json)
          passed=$(jq '.runs[].totals.passed' cypress/results.json)
          emoji=":white_check_mark:"
          if [ "$failed" -gt 0 ]; then
            emoji=":x:"
          fi
          message="$emoji Cypress tests - Passed: $passed Failed: $failed"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$message"'"}' https://slack.com/api/chat.postMessage
        env:
          SLACK_CHANNEL: cypresstest
          SLACK_COLOR: "#9e2a2b"
          #SLACK_ICON: https://someurl.com/logo.png
          SLACK_MESSAGE: "Failed execution on production build"
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
