name: Cypress Tests

on: push
 
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        

      

      - name: Print test results
        if: ${{ always() }}
        run: echo 'Imprimiendo resultados de prueba' && cat cypress/results.json

      - name: Extract test results
        if: ${{ always() }}
        id: extract_results
        run: |
         node -e '
         const fs = require("fs");

         const data = JSON.parse(fs.readFileSync("cypress/results.json"));

         const suites = data.totals.suites;
         const tests =  data.totals.tests;
         const passed = data.totals.passed;
         const failed = data.totals.failed;
         console.log(suites, tests, passed, failed); // debug message to print the extracted values
         console.log(`SUITES=${suites}`); // set environment variable
         console.log(`TESTS=${tests}`); // set environment variable
         console.log(`PASSED=${passed}`); // set environment variable
         console.log(`FAILED=${failed}`); // set environment variable
         ' 
      - name: Print test results
        if: ${{ always() }}
        needs: extract_results
        run: |
          echo "Suites: ${{ env.SUITES }}"
          echo "Tests: ${{ env.TESTS }}"
          echo "Passed: ${{ env.PASSED }}"
          echo "Failed: ${{ env.FAILED }}
       

          
      - name: Send Slack notification
        if: ${{ always() }}
        env:
          SLACK_MESSAGE: "Se ejecutaron ${tests} tests, ${passed} pasaron y ${failed} fallaron"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          SLACK_TITLE: ${{ job.status }}
          SLACK_USERNAME: Deploy Bot
          SLACK_CHANNEL: cypresstest
          SLACK_EMOJI: ":robot_face:"
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "'"${SLACK_MESSAGE}"'"}' $SLACK_WEBHOOK

          
